### ISSUE TITLE
Device may get missing after wake from hibernation

### ISSUE THREAD

**Issue by EraserKing** [irzyxa/Volume2#201] opened 2022-04-04 11:50 UTC
**Describe the bug**
Some audio device may get missing after system goes into hibernation then wakes up. 

I have two output devices:
One is regular speaker output, from front panel on the chassis - connected to the built-in sound card on the motherboard
The other one is the speaker in the monitor - connected via DisplayPort on the discrete graphics card

If I selected the speaker in the monitor as default output device (via Volume2 or Windows own audio device selector), put system into hibernation, then wake up.
Audio still goes to the speaker in the monitor (this is expected), but if I check the device list in Volume2, the monitor speaker is not in the list and instead the regular speaker output is displayed and selected as default. This varies from the actual scenario.

Then, as long as I open the built-in audio device selector of Windows (which is always correct - the monitor speaker is listed there, selected as default output option, as expected), immediately I'll get an additional notification from Volume2 that the default audio output device is turned to the monitor speaker - though there's nothing I changed. I just opened the selector.
After that if I check the Volume2 list, it's correct then: the monitor is displayed as chosen as the default device.

So... as a quick conclusion:
The volume2 may get some devices missing from the list after waken from hibernation (in my scenario it's the monitor speaker via DisplayPort) though it's still acutally working.
And the only way to force it to refresh is to open the Windows own audio device selector (no device change actually needed).

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows version: 11 (21H2)
 - Volume² version: 1.1.7.449

**Additional context**
N/A

**Comment by danielmmmm** [comment] 2022-05-12 19:47
I experience the same issue on Windows 10 with Volume2 v1.1.8.457. My screen with built in speakers (Samsung TV) is connected via HDMI. When my PC wakes up from sleep, the TV is missing from the list of devices in Volume2. Running Volume2 as administrator did not help. Only restarting Volume2 makes it work again.

**Comment by tazazZ** [comment] 2022-11-19 21:45
I also had this issue a lot, I am also using a TV so the device does actually go missing. I use sleep (hybrid sleep, which might not be Hibernation.)
I used to get this problem very often it on my old computer, now not so much. Not sure if a different computer or if this was fixed in a new release.

I use to try the application re-hook setting, but it didn't help, restarting the app was the only way for me too.

**Comment by butgit** [comment] 2023-04-24 15:57
Windows 21H2. Volume<sup>2</sup> 1.1.7.449. 
One of my monitors, which is connected to the PC via HDMI, has in-built speakers for audio output. Sleep settings in Windows make my monitors go to sleep after a few minutes of inactivity, 

Condition: Whenever my monitors are turned on back from sleep mode, 
Description of the issue: 
1. Changing the sound volume by rotating the wheel button on the taskbar does not actually update the physical volume. 
2. The tray icon shows a white x mark enclosed in a red circle. It seems to show that there is something wrong happening.
3. The strange thing is that the OSD **updates** in response to the wheel actions. 

So far, the only way to solve the issue is to restart Volume<sup>2</sup>.

**Comment by chicknsoup** [comment] 2024-09-20 15:02
Same issue here, sound devices with HDMI connection will be lost when the computer wakes up from sleep/hibernation.

**Closed** 2024-09-23 11:39 UTC
Labels: bug, in progress
